### ISSUE TITLE
Make a 'create-[app]' npx module to scaffold new project

### ISSUE THREAD

**Issue by dvalinotti** [litelement-dev/lit-simple-starter-kit#1]
Something that would improve this repo would be to make a 'create-[app]' `npx` or `yarn create` script to scaffold a new project with this starter kit. This starter kit is a great example of using Vite to create Lit web components, and allowing users to run a command in their terminal like `npx create-lit project-name` would make set up even quicker!

I see this project is new, but I have experience making `create-app` scripts so I can contribute if the maintainers would like 😄 

Another option would be to just make this repo a template, but offering a `create-app` script also allows users to select configuration options for their new project.

**Comment by herberthobregon** [comment]
Sure! it would be excellent! I don't really know how to do this type of scripts although I have already seen this with react-app.

For my part I will investigate a little more about this to join it to the repository. If you would like to help create this script and make a pull request, I will be very happy to link it to the master in https://github.com/litelement-dev/create-lit 😃

**Comment by dvalinotti** [comment]
> Sure! it would be excellent! I don't really know how to do this type of scripts although I have already seen this with react-app.
> 
> For my part I will investigate a little more about this to join it to the repository. If you would like to help create this script and make a pull request, I will be very happy to link it to the master in https://github.com/litelement-dev/create-lit 😃

Awesome! I just forked that repo and will start adding the project files 😄
